name: CI/CD Pipeline

on:
  push:
    branches:
      - DEVELOPMENT
  pull_request:
    branches:
      - DEVELOPMENT
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Deploy to Render
        uses: render-examples/deploy-render-action@v1
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          
          
          environment: "production"
